stages:
- build

build:
  stage: build
  image: node:latest
  script:
  - yarn
  - rm -rf ~/slowdowner/*
  - cp -r ./* ~/slowdowner
  - ln -s /media/songs ~/slowdowner/src/static
  - sudo /bin/systemctl restart slowdowner.service