stages:
- build

build:
  stage: build
  image: node:latest
  script:
  - killall node >> /dev/null 2>&1 & true
  - yarn
  - ln -s /media/songs ./src/static
  - yarn run start >> /var/log/slowdowner/access.log 2>&1 & true
