stages:
- build

build:
  stage: build
  image: node:latest
  script:
  - yarn
  - yarn run build
  - rm -rf ~/slowdowner/*
  - cp -r ./* ~/slowdowner
  - ln -s /media/cloud/Musik ~/slowdowner/dist/songs
  - ln -s /media/cloud/Noten ~/slowdowner/dist/sheets
  - sudo /bin/systemctl restart slowdowner.service
  - sudo /bin/systemctl status slowdowner.service